### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Dufiw** [NevaYue/Axion-CS2#1]
Hey, is this your full fixed version or just the normal broken one from T1GxR?

**Comment by NevaYue** [comment]
Up to now,it is avail to inject in cs2. not as same as t1gxr

**Comment by Dufiw** [comment]
okay, I got it injected but it's not showing the menu


using extreme injector with Manual Map & stealth inject

**Comment by Dufiw** [comment]
just tried with xenos and it successfully injects but menu refuses to show/open

**Comment by Dufiw** [comment]
Edit: Nevermind found where the key button is it's "F2" thought it was insert

**Comment by NevaYue** [comment]
hmm,use the release inject. dont close the window before menu shown
